package com.antonio.apprendrebackend.service.exception;

public enum ErrorCode {
    TYPE_NOT_FOUND,
    WORD_TRANSLATION_NOT_FOUND,
    PHRASE_NOT_FOUND,
    HOME_NOT_FOUND,
    GOAL_NOT_CREATED,
    USER_INFO_NOT_FOUND,
    USER_REQUEST_LAST_WEEK_NOT_ANSWERED,
    USER_HISTORIAL,
    DECK_USER_WORD_PHRASE_TRANSLATION,
    WORD_TYPE_NOT_VERB,
    CONJUGATION_VERB_NOT_FOUND,
    VERB_GROUP_NOT_FOUND,
    WORD_NOT_FOUND,
    PERSON_GENDER_NUMBER_NOT_FOUND,
    WORD_COLLECTION_NOT_FOUND,
    WORD_COLLECTION_ITEM_NOT_FOUND,
    TENSE_NOT_FOUND,
    WORD_SENSE_NOT_FOUND,
    CONJUGATION_VARIATION_NOT_FOUND,
    DECK_NOT_FOUND,
    SUCCESS_NOT_FOUND
}